### ISSUE TITLE
META: Various touch screen issues

### ISSUE THREAD

**Issue by Quackdoc** [pop-os/cosmic-files#62]
Im not sure if each of these deserves it's own issue, but here are the various issues regarding touch navigation I have come across. I will add more to these as I come across them, or split them out into separate issues if preferred

- [ ] cannot select options on dropdown like  "settings" "List view" "grid view"
- [ ] Scroll only works when you initially tap a blank area
- [ ] long press file to open context menu
- [ ] dragging the scroll bar is choppy (this may be an issue with my display since it doesn't have the best calibration, but a larger touch area may be better)
